### ISSUE TITLE
Example should be updated for only when PR merges (not just closed)

### ISSUE THREAD

**Issue by kratsg** [carloscastrojumo/github-cherry-pick-action#11]
See documentation here: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-when-a-pull-request-merges

The readme only runs when the PR is closed (which could be a regular close, not when a PR is merged). You need to add `github.event.pull_request.merged` as well as a check.

**Comment by carloscastrojumo** [comment]
Correct @kratsg . `github.event.pull_request.merged == true` needs to be added in the `if` statement. Do you mind open a PR with README update ? 😄

**Comment by navidshaikh** [comment]
PTAL https://github.com/carloscastrojumo/github-cherry-pick-action/pull/57
