### ISSUE TITLE
customized the cherry pick branch name

### ISSUE THREAD

**Issue by litaocdl** [carloscastrojumo/github-cherry-pick-action#18]
if I cherry-pick to muliple branches, the branch name is same for different release branch, that cause conflict. same branch to create pull request and cherry pick but created from different release branches

**Comment by lampajr** [comment]
Hi @litaocdl, have you already done some work on this topic? Otherwise I'm happy to start working on it, since I'll need this improvement too.

**Comment by carloscastrojumo** [comment]
Hey @litaocdl 

in what scenario do you have this? The release branch + git commit SHA should always be unique.
