### ISSUE TITLE
Handling cherry picking on forked repositories

### ISSUE THREAD

**Issue by Confectrician** [carloscastrojumo/github-cherry-pick-action#2]
Hey @carloscastrojumo,

I am using your action in https://github.com/openhab/openhab-docs and had to adapt the workflow file a little due to a different usecase.
Our usecase is to get contributions into different release states of our doc contents, where this action can (and will) save many time.
Therefore we are dealing with contributions based on a forked repository (and base-branch) mostly, which lead to some permission issues with the example configuration.

GitHub has a special event type `pull_request_target` to address this problem:
https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/#improvements-for-public-repository-forks
(My Config: https://github.com/openhab/openhab-docs/blob/main/.github/workflows/cherryPickAutomation.yml#L5)

I would like to avoid the pain for other users and bring this information in place here somehow.
What would be the best way in your view?
Add another example in the readme or just a little note with a link somewhere?
Looking forward to your input. 🙂 

BR
Jerome

**Comment by carloscastrojumo** [comment]
Hello @Confectrician,

I'm very happy to see the tool being useful for other projects. 

Thank you so much for sharing your solution, that will definitely save time to others users, who also have the same use case.

If you don't mind, I would say to make a PR to update the REAME with that special case. 

Cheers,
Carlos
