### ISSUE TITLE
Use pull_request.merge_commit_sha instead of process.env.GITHUB_SHA

### ISSUE THREAD

**Issue by lampajr** [carloscastrojumo/github-cherry-pick-action#44]
**Proposal**

My proposal would be to enhance the action by using `pull_request.merge_commit_sha` instead of `process.env.GITHUB_SHA` as the commit to be cherry picked.

Based on the documentation [1]:
> The value of the `merge_commit_sha` attribute changes depending on the state of the pull request. Before merging a pull request, the `merge_commit_sha` attribute holds the SHA of the test merge commit. After merging a pull request, the `merge_commit_sha` attribute changes depending on how you merged the pull request:
> * If merged as a [merge commit](https://docs.github.com/articles/about-merge-methods-on-github/), merge_commit_sha represents the SHA of the merge commit.
> * If merged via a [squash](https://docs.github.com/articles/about-merge-methods-on-github/#squashing-your-merge-commits), merge_commit_sha represents the SHA of the squashed commit on the base branch.
> * If [rebased](https://docs.github.com/articles/about-merge-methods-on-github/#rebasing-and-merging-your-commits), merge_commit_sha represents the commit that the base branch was updated to.

In order to implement this it should be enough to change from `const githubSha = process.env.GITHUB_SHA` [2] to `const githubSha =  github.context.payload.pull_request.merge_commit_sha`.

> **NOTE**: if the action is triggered using `pull_request_target` event when the pr is closed, `merge_commit_sha` and `process.env.GITHUB_SHA` should coincide.

**Use case**

Consider a simple scenario where we merged a pull request a while ago and we noticed that we forgot to backport it, given the current implementation if we try to use this action with `pull_request_target` workflow event, the `process.env.GITHUB_SHA` [3] could possibly contain a commit sha which differs from the one we were expecting to backport (e.g., using `pull_request_target` event it will contain the last commit on the base branch which could be a different one if new commits have been added on that branch).

> **NOTE**: Another possible way could be to parametrize the commit to be backported, in this way we can keep the default and let callers to override it if needed.

What do you think?

[1] https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request
[2] https://github.com/carloscastrojumo/github-cherry-pick-action/blob/main/src/index.ts#L30
[3] https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target

**Comment by carloscastrojumo** [comment]
Hi @lampajr 

Sorry for the late reply. I agree if your suggestion. Do you mind open a PR?

**Comment by lampajr** [comment]
Hey @carloscastrojumo , no worries!
I'll work on it today :muscle:
