### ISSUE TITLE
dist and src content is differnt

### ISSUE THREAD

**Issue by muthukumarse** [carloscastrojumo/github-cherry-pick-action#5]
I see that in main.ts
const prBranch = `cherry-pick-${inputs.branch}-${githubSha}`
but whereas dist/index.js
const prBranch = `cherry-pick-${githubSha}`;

how come? i looking option to add cherry-pick-[XXXX]

**Comment by carloscastrojumo** [comment]
`dist` was indeed outdated. Just released a new version @muthukumarse please check it out.
