### ISSUE TITLE
Ability to setup the PR title and description in created PR

### ISSUE THREAD

**Issue by radtriste** [carloscastrojumo/github-cherry-pick-action#9]
Hi @carloscastrojumo 

Is there a way to setup the title and description of the created PR via inputs ?
If not, do you mind if I create a PR for it ?

Regards
Tristan

**Comment by radtriste** [comment]
Here are my thoughts about this and why I ask... 
In the created PR I would like to have:
- the targeted branch name into the title
- a link to cherry-picked PR in the newly created PR

**Comment by carloscastrojumo** [comment]
Thank you for the contribution.
